#!/usr/bin/bash

# make pour construire le binaire
# clean pour nettoyer le répertoire

if ( ! test -z $1 ); then
    case $1 in 
	"make")
            mkdir src 2> /dev/null
	    yacc -d yacc.y -o src/yacc.c
	    lex -t -d lex.l > src/lex.c
	    gcc src/yacc.c src/lex.c -o prog -ly -lfl
	    ;;
	"clean")
	    rm src/*.c src/*.h prog *~ exemples/*~ 2> /dev/null 
	    ;;
	*) echo "Usage: <make|clean>" ;;
    esac
else
    echo "Usage: <make|clean>"
fi

